@BIBINPUTS = ('.', '../', '../bibs');
$latex = 'TEXINPUTS="$TEXINPUTS:../:../dist:./templates" uplatex';
$bibtex = 'BIBINPUTS="$BIBINPUTS:../:../bibs" BSTINPUTS="$BSTINPUTS:./templates" upbibtex';
$dvipdf = 'OSFONTDIR="$OSFONTDIR:./fonts" dvipdfmx %O -o %D %S';
$makeindex = 'mendex -U %O -o %D %S';
$pdf_mode = 3;
