@BIBINPUTS = ('.', '../', '../bibs');
$latex = 'TEXINPUTS="$TEXINPUTS:./templates" platex';
$bibtex = 'BIBINPUTS="$BIBINPUTS:../:../bibs" BSTINPUTS="$BSTINPUTS:./templates" pbibtex';
$dvipdf = 'OSFONTDIR="$OSFONTDIR:./fonts" dvipdfmx %O -o %D %S';
$makeindex = 'mendex -U %O -o %D %S';
$pdf_mode = 3;
